### PR TITLE
DEFER: Add graphql caching and improve freezing of table objects

### PR DESCRIPTION
**Pull request by AjBreidenbach**

### CODE REVIEW

**Comment by AjBreidenbach** [comment]
Requires https://github.com/onecommons/gitlab-oc/pull/1078

**Comment by aszs** [comment]
@AjBreidenbach let's split out the freeze logic into a separate PR and I'll merge that in first

**Comment by aszs** [comment]
> @AjBreidenbach let's split out the freeze logic into a separate PR and I'll merge that in first

this was merged in #174

**Comment by AjBreidenbach** [comment]
This PR is completely redundant with unfurl-server

**Pull request closed without merging**
