### PR TITLE
add formily support generic object json-schema type

### PR DESCRIPTION
**Pull request by jxianc**

### CODE REVIEW

**Comment by aszs** [comment]
@jxianc looks good! I will pull and play with it. Do we need to do anything to serialize the form values or will it automatically create the json object with user specified keys and values?

**Comment by AjBreidenbach** [comment]
@aszs he ran this by me earlier, from what he saw in the dev tools it was serializing correctly
image

**Comment by aszs** [comment]
I tried to reply via email but github didn't add that as a comment.. but this is what i wrote:

> @aszs he ran this by me earlier, from what he saw in the dev tools it looks like it was serializing correctly !

Ok that's not correct... It's supposed to be a Javascript object / map so we'll have to convert this array to a object... something like:

        _.object(_.map(value, v => [v.key, v.value]))

**Comment by AjBreidenbach** [comment]
@jxianc we can try serializing this to match that shape in oc-inputs, but outside of formily if that's easier

**Comment by AjBreidenbach** [comment]
I noticed that this also doesn't save and deserialize correctly, but we needed to change the shape anyway

**Comment by AjBreidenbach** [comment]
Going to open a PR against handover instead

**Comment by aszs** [comment]
Ok that's not correct... It's supposed to be a Javacript object / map so
we'll have to convert that array to that

**Pull request closed without merging**
